# Common build stage
FROM node:17-alpine as common-build-stage

COPY . ./app

WORKDIR /app

RUN npm install 

# Development build stage

FROM common-build-stage as development-build-stage

RUN npm install -g nodemon

ENV NODE_ENV development

CMD ["npm", "run", "dev"]